{"name": "test_NAF_2_2_0_login_with_wrong_email", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/qingqinfang/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)", "trace": "tests/android/test_2_Authentication.py:95: in test_NAF_2_2_0_login_with_wrong_email\n    raise e\ntests/android/test_2_Authentication.py:88: in test_NAF_2_2_0_login_with_wrong_email\n    login_page.login(Config.TEST_EMAIL_WRONG, Config.TEST_PASSWORD)\npages/android/login_page.py:201: in login\n    self.wait_for_welcome_screen()\npages/android/login_page.py:33: in wait_for_welcome_screen\n    self.wait_for_element_visible(*self.WELCOME_TEXT_1, timeout=10)\ncore/base_page.py:131: in wait_for_element_visible\n    element = wait.until(EC.visibility_of_element_located((By.XPATH, locator_value)))\nvenv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py:101: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message: \nE   Stacktrace:\nE   NoSuchElementError: An element could not be located on the page using the given search parameters.\nE       at AndroidUiautomator2Driver.findElOrEls (/Users/qingqinfang/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)\nE       at processTicksAndRejections (node:internal/process/task_queues:105:5)\nE       at AndroidUiautomator2Driver.findElOrElsWithProcessing (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\nE       at AndroidUiautomator2Driver.findElement (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)"}, "description": "\n    Test Case: NAF-15\n    As a user, I want to log in with my email and password\n    Scenario: Login Unsuccessful due to Non-existent Email\n    \n    Steps:\n    1. Open the app\n    2. Click on \"Log in\" button\n    3. Click on \"Sign in with your email\" button\n    4. Enter non-existent email: test@example.com\n    5. Enter password: testpassword\n    6. Click \"Log in\" button    \n    7. Verify error message appears\n    \n    Expected Result: Error message \"There is no account associated with this email. Please sign up.\" should be displayed\n    ", "start": 1753447813287, "stop": 1753447829281, "uuid": "b609b3d2-7a51-4d51-9a43-4aac2e0da412", "historyId": "b16a29071b6a401b6486a6fc183d32f0", "testCaseId": "b16a29071b6a401b6486a6fc183d32f0", "fullName": "tests.android.test_2_Authentication.TestAuthentication#test_NAF_2_2_0_login_with_wrong_email", "labels": [{"name": "story", "value": "2.2.0 As a user, I want to log in with my email and password"}, {"name": "epic", "value": "Mobile App Testing-Android"}, {"name": "feature", "value": "2.0.0 Authentication"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "authentication"}, {"name": "parentSuite", "value": "tests.android"}, {"name": "suite", "value": "test_2_Authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "fqqqqq.local"}, {"name": "thread", "value": "75454-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.android.test_2_Authentication"}]}